apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: http-echo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
        - "-text=Hello from {{ .Release.Name }}!"
        ports:
        - containerPort: 5678
