{{- if .Values.ingress.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: copy-wildcard-tls
  namespace: {{ .Release.Namespace }}
  annotations:
    # run before install & upgrade, and then delete itself
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      # so it can call the API with RBAC we already granted
      serviceAccountName: argocd-application-controller
      containers:
        - name: copy-secret
          # small image with kubectl
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "Copying wildcard cert into {{ .Release.Namespace }}"
              kubectl get secret web-wildcard-tls -n test-tls -o yaml \
                | sed "s/namespace: test-tls/namespace: {{ .Release.Namespace }}/" \
                | kubectl apply -f -
      restartPolicy: OnFailure
{{- end }}
