{{- if .Values.ingress.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: copy-wildcard-tls-{{ .Release.Name }}
  namespace: argocd
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: argocd-application-controller
      containers:
      - name: copy-secret
        image: bitnami/kubectl:1.27.3
        command:
          - /bin/sh
          - -c
          - |
            set -eux
            echo "Copying web-wildcard-tls into {{ .Release.Namespace }}…"
            kubectl get secret web-wildcard-tls -n test-tls -o yaml \
              | sed "s/namespace: test-tls/namespace: {{ .Release.Namespace }}/" \
              | kubectl apply -f -
      restartPolicy: OnFailure
{{- end }}
