{{- if .Values.ingress.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  # Unique per‐release
  name: copy-wildcard-tls-{{ .Release.Name }}
  # Always create this job in the argocd namespace
  namespace: argocd
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      # Use the exact SA that exists in argocd
      serviceAccountName: argocd-application-controller
      containers:
      - name: copy-secret
        image: bitnami/kubectl:latest
        command:
          - /bin/sh
          - -eux
          - |
            echo "Copying web-wildcard-tls into {{ .Release.Namespace }}…"
            kubectl get secret web-wildcard-tls -n test-tls -o yaml \
              | sed "s/namespace: test-tls/namespace: {{ .Release.Namespace }}/" \
              | kubectl apply -f -
      restartPolicy: OnFailure
{{- end }}
