replicaCount: 1

image:
  repository: ghcr.io/frallan97/hello-app
  tag: "0.1.0"

service:
  port: 80

ingress:
  enabled: true
  # Namespace where wildcard secret currently lives:
  # TLS settings
  tls:
    - hosts:
        - hello-app.web.franssjostrom.com
      secretName: web-wildcard-tls
  # Rules
  hosts:
    - host: hello-app.web.franssjostrom.com
      paths:
        - path: /
          pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
